# Generated by Django 5.2.9 on 2025-12-11 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('submission_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_workers', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('in_progress_count', models.PositiveIntegerField(default=0)),
                ('complete_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('late_overdue_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('late_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('avg_files_per_submission', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('deadline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='submission_settings.reportdeadlinesetting')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_analytics', to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('complete_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='submission_settings.reportanalytics')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='UserSubmissionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('on_time_submissions', models.PositiveIntegerField(default=0)),
                ('late_submissions', models.PositiveIntegerField(default=0)),
                ('average_submission_delay_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_files_uploaded', models.PositiveIntegerField(default=0)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentDeadlineAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('complete', models.PositiveIntegerField(default=0)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('late', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_analytics', to='submission_settings.reportdeadlinesetting')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_by_deadline', to='accounts.department')),
            ],
            options={
                'unique_together': {('deadline', 'department')},
            },
        ),
    ]
