# Generated by Django 5.2.9 on 2025-12-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_settings', '0002_reportanalytics_reportanalyticssnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('late', 'Late'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
    ]
