# Generated by Django 5.2.9 on 2025-12-23 04:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('matrix_a', 'Matrix A'), ('matrix_b', 'Matrix B'), ('mov', 'MOV')], db_index=True, max_length=20)),
                ('file', models.FileField(upload_to='work_items/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], db_index=True, max_length=50)),
                ('message', models.TextField(help_text='Message regarding status, review, or work clarification')),
                ('related_status', models.CharField(blank=True, help_text='Status this message refers to (optional)', max_length=30)),
                ('related_review', models.CharField(blank=True, help_text='Review decision this message refers to (optional)', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('position_title', models.CharField(blank=True, help_text='Job title or designation', max_length=150)),
                ('login_role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], db_index=True, default='user', help_text='Defines access level inside the system', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official organizational unit name', max_length=150)),
                ('team_type', models.CharField(choices=[('division', 'Division'), ('section', 'Section'), ('service', 'Service'), ('unit', 'Unit')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description or mandate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent organizational unit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.team')),
            ],
            options={
                'ordering': ['team_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Team Lead'), ('member', 'Member')], default='member', help_text='Role of the user within the team', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team__name'],
            },
        ),
        migrations.CreateModel(
            name='WorkCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task, report, or work cycle', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional details or instructions')),
                ('due_at', models.DateTimeField(help_text='Deadline for this work cycle')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive work cycles are archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this work cycle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workcycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_team', models.ForeignKey(blank=True, help_text='Assign to a team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='accounts.team')),
                ('assigned_user', models.ForeignKey(blank=True, help_text='Assign directly to a specific user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to=settings.AUTH_USER_MODEL)),
                ('workcycle', models.ForeignKey(help_text='Work cycle being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.workcycle')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive items are archived or closed for a specific reason')),
                ('inactive_reason', models.CharField(blank=True, choices=[('reassigned', 'Reassigned'), ('duplicate', 'Duplicate Submission'), ('invalid', 'Invalid / Not Required'), ('superseded', 'Superseded by New Submission'), ('archived', 'Archived After Completion')], db_index=True, help_text='Reason why this work item became inactive', max_length=50)),
                ('inactive_note', models.CharField(blank=True, help_text='Optional explanation or comment', max_length=255)),
                ('inactive_at', models.DateTimeField(blank=True, help_text='Timestamp when this item became inactive', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('working_on_it', 'Working on It'), ('done', 'Done (Submitted)')], db_index=True, default='not_started', max_length=30)),
                ('status_label', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('review_decision', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('revision', 'Needs Revision')], db_index=True, default='pending', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to=settings.AUTH_USER_MODEL)),
                ('workcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='accounts.workcycle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
