# Generated by Django 5.2.9 on 2025-12-13 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive items are archived due to reassignment'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='review_decision',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('revision', 'Needs Revision')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('working_on_it', 'Working on It'), ('done', 'Done (Submitted)')], db_index=True, default='not_started', max_length=30),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='status_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='workcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='accounts.workcycle'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['is_active'], name='accounts_wo_is_acti_98b501_idx'),
        ),
    ]
